### ISSUE TITLE
Garage system esx_policejob / ambulancejob

### ISSUE THREAD

**Issue by PWajong** [esx-framework/esx_policejob#35]
When u bought the vehicle as  police / ambulance  and u lose the car of or it broke down cant take the car out of the garage because it says u didnt park it,

Is there a possibility to make the garage system for police and ambulance the same like the taxijob?  

Just spawn the cars as many as u like ,  and delete it in a red circle  , with this system u dont have the problem that the people need to buy the cars over and over again, or change that u can always spawn the vehicle.

I know u cant set cars to a rank like the police and ambulance job but i dont see this as a problem.

I hope this problem can be fixed!

Grtz Patrick

**Comment by Gellipapa** [comment]
@PWajong Hi! This is not a bug.  

It's done this way on purpose because on an RP server they play in such a way that if they take a car out of the garage they can't take it out again so they are protected against spamming. 

Now imagine that I buy a motorbike on an RP server and because I can spawn infinitely I can give my motorbike to 5 people at once. 

That's why it's not done that way, but as a feature I'll write it down and if we have time we'll do it. 

Thanks for your comment.
